ADD: check if magento to all steps

diff --git a/mage b/mage
--- a/mage
+++ b/mage
@@ -3,6 +3,12 @@
 # Mage is collection of easy cmd's and alias for bin/magento
 # For those that hate typing long shell cmd's
 
+# Exit early, if not Magento 2
+if [[ ! -d app/etc ]]; then
+  echo "This does not look like the Magento 2 root folder, aborting.." && exit 1;
+fi
+
+
 RESET='\033[0m'
 BOLD='\033[1m'
 ITALIC='\033[3m'
@@ -250,7 +256,6 @@ case "${@}" in
   ;;
 
 "add sample")
-  if [[ ! -d app/etc ]]; then echo "This does not look like the Magento 2 root folder, aborting.." && exit 1; fi
   read -p "What is your Magento base version (sample: 2.4): " MVERSION && echo ""
   if [[ -z "$MVERSION" ]]; then echo "The Magento 2 version is empty, aborting.." && exit 1; fi
 
@@ -270,8 +275,6 @@ case "${@}" in
   ;;
 
 "add hyva")
-  if [[ ! -d app/etc ]]; then echo "This does not look like the Magento 2 root folder, aborting.." && exit 1; fi
-
   echo "Installing Hyva theme..."
   echo "Make sure you have and license key or access to the gitlab env"
   echo "else cancel with Ctrl+C"
