Release v1.12

diff --git a/mage b/mage
--- a/mage
+++ b/mage
@@ -4,9 +4,9 @@
 # For those that hate typing long shell cmd's
 
 # Exit early, if not Magento 2
-# if [[ ! -d app/etc ]]; then
-#   echo "This does not look like the Magento 2 root folder, aborting.." && exit 1;
-# fi
+if [[ ! -d app/etc ]]; then
+  echo "This does not look like the Magento 2 root folder, aborting.." && exit 1;
+fi
 
 # Global variables
 RESET='\033[0m'
