IMP: build

diff --git a/mage b/mage
--- a/mage
+++ b/mage
@@ -188,6 +188,32 @@ function mage_help() {
 }
 
 
+function mage_add_sample() {
+  read -p "What is your Magento base version (sample: 2.4): " MVERSION && echo ""
+  if [[ -z "$MVERSION" ]]; then echo "The Magento 2 version is empty, aborting.." && exit 1; fi
+
+  if [[ ! -d "$HOME/.magento-sampledata/$MVERSION" ]]; then
+    git clone -b $MVERSION git@github.com:magento/magento2-sample-data.git $HOME/.magento-sampledata/$MVERSION
+  fi
+
+  echo -e "Installing $MVERSION sample data"
+  # Lets make sure these folder exist, to prevent them being made as a symlink
+  mkdir -p app/code/Magento
+  mkdir -p pub/media/catalog/product
+  mkdir -p pub/media/downloadable/files
+  mkdir -p pub/media/wysiwyg
+  touch README.md
+  php -f $HOME/.magento-sampledata/$MVERSION/dev/tools/build-sample-data.php -- --ce-source="$PWD"
+  $MAGENTO_CLI setup:upgrade
+
+  # Set theme to Hyva if present
+  if composer show hyva-themes/magento2-default-theme >/dev/null 2>&1; then
+    if composer show yireo/magento2-theme-commands >/dev/null 2>&1; then
+      $MAGENTO_CLI theme:change Hyva/default
+    fi
+  fi
+}
+
 case "${@}" in
 "version" | "-v" | "--version")
   mage_version
@@ -290,7 +316,8 @@ case "${@}" in
 
 "purge"*)
   CLEANTASKS=(
-    'generated/*'
+    'generated/metadata/*'
+    'generated/code/*'
     'pub/static/adminhtml/*'
     'pub/static/frontend/*'
     'var/cache/*'
@@ -375,29 +402,7 @@ case "${@}" in
   ;;
 
 "add sample")
-  read -p "What is your Magento base version (sample: 2.4): " MVERSION && echo ""
-  if [[ -z "$MVERSION" ]]; then echo "The Magento 2 version is empty, aborting.." && exit 1; fi
-
-  if [[ ! -d "$HOME/.magento-sampledata/$MVERSION" ]]; then
-    git clone -b $MVERSION git@github.com:magento/magento2-sample-data.git $HOME/.magento-sampledata/$MVERSION
-  fi
-
-  echo -e "Installing $MVERSION sample data"
-  # Lets make sure these folder exist, to prevent them being made as a symlink
-  mkdir -p app/code/Magento
-  mkdir -p pub/media/catalog/product
-  mkdir -p pub/media/downloadable/files
-  mkdir -p pub/media/wysiwyg
-  touch README.md
-  php -f $HOME/.magento-sampledata/$MVERSION/dev/tools/build-sample-data.php -- --ce-source="$PWD"
-  $MAGENTO_CLI setup:upgrade
-
-  # Set theme to Hyva if present
-  if composer show hyva-themes/magento2-default-theme >/dev/null 2>&1; then
-    if composer show yireo/magento2-theme-commands >/dev/null 2>&1; then
-      $MAGENTO_CLI theme:change Hyva/default
-    fi
-  fi
+  mage_add_sample
   ;;
 
 "add hyva")
@@ -414,17 +419,32 @@ case "${@}" in
   ;;
 
 "set hyva")
-  $MAGENTO_CLI theme:change Hyva/default
-  $MAGENTO_CLI cache:flush
+  mage set theme Hyva/default
   ;;
 
 "set baldr")
-  $MAGENTO_CLI theme:change Siteation/baldr
-  $MAGENTO_CLI cache:flush
+  mage set theme Siteation/baldr
   ;;
 
-"config")
+"set mode"*)
+  DEPLOY_MODE="developer"
+  IS_MODE_PROD=0
+  ADMIN_SESSION_LIFETIME=86400 # 24h in seconds
+  ADMIN_PASSWORD_LIFETIME=0
 
+  if [[ $3 == "production" ]] || [[ $3 == "prod" ]]; then
+    DEPLOY_MODE="production"
+    IS_MODE_PROD=1
+    ADMIN_SESSION_LIFETIME=43200 # 12h in seconds
+    ADMIN_PASSWORD_LIFETIME=90 # days
+  fi
+
+  $MAGENTO_CLI config:set dev/static/sign $IS_MODE_PROD > /dev/null 2>&1
+  $MAGENTO_CLI config:set admin/captcha/enable $IS_MODE_PROD > /dev/null 2>&1
+  $MAGENTO_CLI config:set admin/security/session_lifetime $ADMIN_SESSION_LIFETIME > /dev/null 2>&1
+  $MAGENTO_CLI config:set admin/security/password_lifetime $ADMIN_PASSWORD_LIFETIME > /dev/null 2>&1
+  $MAGENTO_CLI config:set admin/security/password_is_forced $IS_MODE_PROD > /dev/null 2>&1
+  $MAGENTO_CLI deploy:mode:set $DEPLOY_MODE
   ;;
 
 "build"*)
